stages:
  - deploy

variables:
  GOFLAGS: "-count=1" # Supersedes GOCACHE=off, see: https://github.com/golang/go/issues/29378#issuecomment-449383809

build:
  stage: deploy
  image: golang:1.13
  tags: [go]
  script:
    - git fetch origin --prune +refs/heads/*:refs/heads/*
    - go run mage.go -v ci
